name = "text-generation"
main = "_worker.js"
compatibility_date = "2024-10-31"
preview_urls = false
keep_vars = true

[vars]
ACCOUNT_ID = "xxxxxxxxxxxxxxxxx"
API_TOKEN = "xxxxxxxxxxxxxxxxx"
API_KEY = "sk-xxxxxxxxxxxxxxxxx"
STREAM = "true"

[ai]
binding = "AI"
